### ISSUE TITLE
OSX 10.12 Library not loaded

### ISSUE THREAD

**Issue by ghost** [conda-forge/netcdf4-feedstock#30]
Hello, I am trying to run a script that reads a netcdf file, and get the following error:

Traceback (most recent call last):
  File "/Users/turekg/dev/python/workspace/NCEP/src/ncep_ensemble_creator", line 272, in <module>
    main(sys.argv[1:])
  File "/Users/turekg/dev/python/workspace/NCEP/src/ncep_ensemble_creator", line 263, in main
    dset_out.to_netcdf(join(outputDir, "tn_{:%Y%m%d}06-utc_ncep_21.nc".format(date)), format='NETCDF3_CLASSIC', engine='netcdf4')
  File "/Users/turekg/dev/python/anaconda27/lib/python2.7/site-packages/xarray/core/dataset.py", line 786, in to_netcdf
    engine=engine, encoding=encoding)
  File "/Users/turekg/dev/python/anaconda27/lib/python2.7/site-packages/xarray/backends/api.py", line 351, in to_netcdf
    store = store_cls(path, mode, format, group, writer)
  File "/Users/turekg/dev/python/anaconda27/lib/python2.7/site-packages/xarray/backends/netCDF4_.py", line 177, in __init__
    import netCDF4 as nc4
  File "/Users/turekg/dev/python/anaconda27/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/turekg/dev/python/anaconda27/lib/python2.7/site-packages/netCDF4/_netCDF4.so, 2): Library not loaded: @rpath/libmfhdf.0.dylib
  Referenced from: /Users/turekg/dev/python/anaconda27/lib/python2.7/site-packages/netCDF4/_netCDF4.so
  Reason: image not found

I am using python 2.7, conda 4.2.13, netcdf4 1.2.7 and hdf5 1.8.17 are installed

**Comment by ghost** [comment]
I fixed this by removing hdf4 (which caused libnetcdf and netcdf4 to be removed) and re-installing netcdf4

**Comment by ocefpaf** [comment]
Please take a look at https://github.com/conda-forge/conda-forge.github.io/pull/325#issuecomment-276863782 which may explain what happened there.
