### ISSUE TITLE
netcdf4<1.4.0 + gdal

### ISSUE THREAD

**Issue by bekozi** [conda-forge/netcdf4-feedstock#52]
`netcdf4` added some improvements in the `1.4.0` release. They are unfortunately backwards incompatible. I am hoping to get a `netcdf4<1.4.0` build that is compatible with `gdal`. Right now I get:
```
$ conda install -c conda-forge "netcdf4<1.4.0" gdal
$ python -c "import osgeo"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/ocgis/__init__.py", line 5, in <module>
    import osgeo
  File "/opt/conda/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/opt/conda/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/opt/conda/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
```
Is there a trick I should be using? Can we get a working build for `netcdf4<1.4.0`+`gdal`? Upgrading to the new `cftime` was not bad, but I'd like for code built on older `netcdf4` to be supported on conda-forge until we get a new one out. Thanks!

**Comment by ocefpaf** [comment]
We would need to rebuild a version of `netcdf<1.4.0`. If you want to open a PR for that I can create a branch for the version that works for you.

**Comment by bekozi** [comment]
Works. Thanks @ocefpaf

**Comment by ocefpaf** [comment]
I did not do anything, you sent the PR, I just merged it ;-p
