### ISSUE TITLE
Import failure due to libssh2 issue

### ISSUE THREAD

**Issue by djgagne** [conda-forge/netcdf4-feedstock#88]
Issue: When importing netCDF4, I ran into the following error:
```python
>>> from netCDF4 import Dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dgagne/miniconda3/envs/ml/lib/python3.6/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/dgagne/miniconda3/envs/ml/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/dgagne/miniconda3/envs/ml/lib/libssh2.1.dylib
  Reason: image not found
```
I was able to fix the problem by manually updating libssh2 from 1.8.0-1 to 1.8.2-hcdc9a53_2. However, updating netcdf with
`conda update netcdf4` only upgraded the netcdf4 binary but not the libssh2 binary. Is there a way to fix the dependencies to make sure libssh2 also updates when updating netcdf4? I am currently running on macOS 10.13.6 (High Sierra). 
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/dgagne/miniconda3/envs/ml:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.0                    pypi_0    pypi
alabaster                 0.7.12                     py_0    conda-forge
ams-ml-python-course      0.1                       dev_0    <develop>
appnope                   0.1.0                 py36_1000    conda-forge
astor                     0.7.1                    pypi_0    pypi
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                   pypi_0    pypi
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      2.5                    openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.15.1            h0a44026_1002    conda-forge
bokeh                     1.0.4                 py36_1000    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cartopy                   0.17.0          py36h929c6f0_1004    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cftime                    1.0.3.4         py36h917ab60_1000    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.7.0                      py_0    conda-forge
curl                      7.64.0               heae2a1f_2    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cytoolz                   0.9.0.1         py36h1de35cc_1001    conda-forge
dask                      1.1.4                      py_0    conda-forge
dask-core                 1.1.4                      py_0    conda-forge
decorator                 4.3.2                      py_0    conda-forge
distributed               1.26.0                   py36_1    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
ephem                     3.7.6.0         py36h1de35cc_1001    conda-forge
freetype                  2.9.1             h597ad8a_1005    conda-forge
gast                      0.2.2                    pypi_0    pypi
geos                      3.7.1             h0a44026_1000    conda-forge
grpcio                    1.18.0                   pypi_0    pypi
h5py                      2.9.0                    pypi_0    pypi
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h646315f_1105    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipykernel                 5.1.0           py36h24bf2e0_1002    conda-forge
ipython                   7.2.0           py36h24bf2e0_1000    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jinja2                    2.10                     pypi_0    pypi
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter-console           6.0.0                    pypi_0    pypi
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.7                    pypi_0    pypi
keras-preprocessing       1.0.9                    pypi_0    pypi
kiwisolver                1.0.1           py36h04f5b5a_1002    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0                5_openblas    conda-forge
libcblas                  3.8.0                5_openblas    conda-forge
libcurl                   7.64.0               he376013_2    conda-forge
libcxx                    7.0.0                h2d50403_2    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h0a44026_1005    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h1de35cc_1004    conda-forge
liblapack                 3.8.0                5_openblas    conda-forge
liblapacke                3.8.0                5_openblas    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.36            ha441bb4_1000    conda-forge
libsodium                 1.0.16            h1de35cc_1001    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.10            h79f4b77_1001    conda-forge
libxml2                   2.9.8             hf14e9c8_1005    conda-forge
libxslt                   1.1.32            h33a18ac_1002    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
llvmlite                  0.26.0          py36h3fea490_1000    conda-forge
locket                    0.2.0                      py_2    conda-forge
lorenz-gan                0.1                       dev_0    <develop>
lxml                      4.3.1            py36h7166777_0    conda-forge
markdown                  3.0.1                    pypi_0    pypi
markupsafe                1.1.0           py36h1de35cc_1000    conda-forge
matplotlib                3.0.2                 py36_1002    conda-forge
matplotlib-base           3.0.2           py36hf043ca5_1002    conda-forge
mistune                   0.8.4           py36h1de35cc_1000    conda-forge
mlmicrophysics            0.1                       dev_0    <develop>
mlsurfacelayer            0.1                       dev_0    <develop>
mock                      2.0.0                    pypi_0    pypi
more-itertools            4.3.0                 py36_1000    conda-forge
msgpack-python            0.6.1            py36h04f5b5a_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
netcdf-fortran            4.4.5             h5ce9b53_1000    conda-forge
netcdf4                   1.5.1.2          py36h58b02fa_0    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numba                     0.41.0          py36h1702cab_1000    conda-forge
numexpr                   2.6.9           py36h1702cab_1000    conda-forge
numpy                     1.16.3           py36hdf140aa_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
owslib                    0.17.1                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.1           py36h0a44026_0    conda-forge
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.4                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
pbr                       5.1.3                    pypi_0    pypi
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.4.1           py36hbddbef0_1000    conda-forge
pip                       19.0.2                   py36_0    conda-forge
pluggy                    0.11.0                     py_0    conda-forge
proj4                     5.2.0             h1de35cc_1001    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.8                      py_0    conda-forge
protobuf                  3.6.1                    pypi_0    pypi
psutil                    5.5.0            py36h1de35cc_0    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pvlib-python              0.6.1                      py_0    conda-forge
py                        1.8.0                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pykdtree                  1.3.1           py36h917ab60_1002    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.6           py36h9c430a6_1000    conda-forge
pyqt                      5.6.0           py36hc26a216_1008    conda-forge
pyrsistent                0.14.10          py36h1de35cc_0    conda-forge
pyshp                     2.0.1                      py_0    conda-forge
pytables                  3.4.4           py36h0af8b44_1004    conda-forge
pytest                    4.4.2                    py36_0    conda-forge
python                    3.6.7             h8dc6b48_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13            py36h1de35cc_1001    conda-forge
pyzmq                     17.1.2          py36h111632d_1001    conda-forge
qt                        5.6.2             h822fa55_1013    conda-forge
qtconsole                 4.4.3                    pypi_0    pypi
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.13.0                   py36_0    conda-forge
scikit-learn              0.20.2          py36_blas_openblashc6dc708_1400  [blas_openblas]  conda-forge
scipy                     1.2.0           py36_blas_openblash486cb9f_1201  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
shapely                   1.6.4           py36h2bcc7ef_1002    conda-forge
sip                       4.18.1          py36h0a44026_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    1.8.4                    py36_0    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
sqlite                    3.26.0            h1765d9f_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tensorboard               1.13.1                   pypi_0    pypi
tensorflow                1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
tensorflow-probability    0.6.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
tk                        8.6.9             ha441bb4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py36h1de35cc_1000    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  0.14.1                   pypi_0    pypi
wheel                     0.33.0                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
xarray                    0.11.3                   py36_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zeromq                    4.2.5             h0a44026_1006    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
active environment : ml
    active env location : /Users/dgagne/miniconda3/envs/ml
            shell level : 1
       user config file : /Users/dgagne/.condarc
 populated config files : /Users/dgagne/.condarc
                          /Users/dgagne/miniconda3/envs/ml/.condarc
          conda version : 4.6.3
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : /Users/dgagne/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/dgagne/miniconda3/pkgs
                          /Users/dgagne/.conda/pkgs
       envs directories : /Users/dgagne/miniconda3/envs
                          /Users/dgagne/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.3 requests/2.18.4 CPython/3.6.8 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 493664989:1202617992
             netrc file : None
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
It is really odd you got such an old `libssh2` package (pre conda-build 3 b/c of the absence of the hash build number). Probably a package with bad metadata. Removed those from `main` and hopefully that should fix your problem.
